### ISSUE TITLE
Download samples from nana-music

### ISSUE THREAD

**Issue by zhang-jian** [dhgrs/chainer-ClariNet#10]
I want to analysis the samples, but seems that they cannot be downloaded from nana-music. Is there any chance you can share your samples in a different way?

Thanks,

**Comment by dhgrs** [comment]
Hi,

Sorry for late reply. I uploaded samples in Google Drive.
https://drive.google.com/drive/folders/1Z2w7Q1OMCvlNkS-F_XLCl0QyrZDf5VCi?usp=sharing
I applied postprocessing in 576060561ba8b5a7b5e03d5c01aed4213cfbb6df for `StudentGaussianIAFLJSpeechwithPostprocessing.wav`.

**CAUTION**:
I trained my model with a different setting.
- Sampling rate is 24kHz (22.05kHz in repo)
- Use VCTK-Corpus to train Teacher (LJSpeech in repo)

**Comment by zhang-jian** [comment]
Thank you!
