### ISSUE TITLE
Sampling after Student network

### ISSUE THREAD

**Issue by zhang-jian** [dhgrs/chainer-ClariNet#2]
Hi,

Thanks for sharing.

It seems that there is an **_extra_** sampling step after the student network at https://github.com/dhgrs/chainer-ClariNet/blob/master/StudentGaussianIAF/net.py#L58 to get student samples. However, `Algorithm 1` in https://arxiv.org/pdf/1807.07281.pdf uses z from the last IAF flow as student samples. What is the motivation of making such change?

Thanks,

Jian

**Comment by dhgrs** [comment]
Hi,

Parallel WaveNet in my implementation does not apply scaling and shifting in the last flow. So that we need scaling and shifting to get `x = z^(n)`.

Not only `x` but also means and log scales are needed to calculate loss. That is why I implement as this.

**Comment by zhang-jian** [comment]
Sorry for the late reply, it is clear now. Thanks.
