### ISSUE TITLE
loss curve

### ISSUE THREAD

**Issue by dukanov** [dhgrs/chainer-ClariNet#3]
Could you provide your loss plot from training autoregressive wavenet?
I've started training model with your implementation and have got following loss "jump". Is it OK?
![loss](https://user-images.githubusercontent.com/22235295/45962124-cfa93d80-c028-11e8-9c14-9551c4dda9c6.png)

**Comment by dhgrs** [comment]
Hi,

The loss sometimes jumps until about 50k iterations. But the training goes well. This is my loss curve with VCTK-Corpus. 
![loss](https://user-images.githubusercontent.com/22191150/46017241-fd1de600-c111-11e8-90fd-ac972bf40c2c.png)

If you uses 6842fcf0d860d5652ef98bfc0b29aae1b58a8ada , the loss is much more unstable. Please pull the newest commit.

**Comment by dukanov** [comment]
Thanks!
