### ISSUE TITLE
AutoregressiveWaveNet generates only silence

### ISSUE THREAD

**Issue by zuzana** [dhgrs/chainer-ClariNet#4]
Hi, 

I have trained AutoregressiveWaveNet using command from README.md

```
python train.py -g 0
```

Then I have tried to generate audio using command from README.md

```
python generate.py -i ../../LJSpeech-1.1/wavs/LJ001-0001.wav -o result.wav -m 2018_09_27_16_03_22/snapshot_iter_500000 -g 0
```

Generated audio was completely silent, do you have any tip what could have gone wrong?

Thanks.

**Comment by dhgrs** [comment]
Hi,

Thanks for your trial and sorry for the bug.
In ORIGINAL Parallel WaveNet paper, output signals are scaled into [-127.5, 127.5]. So apply `x / 127.5` in `generate.py`.
In ClariNet paper, output signals are not scaled. So we don't need scaling in `generate.py`.

I pushed a bug-fix commit 6041db7d1aef43ada84a97e95fcddf1164362aba in develop branch. Can you try this? If it works, I'll merge it into master branch.

**Comment by dhgrs** [comment]
BTW `-p` and `-f` option may accelerate the training. Like `python train.py -g 0 -p 2 -f 64`. Details are in README.

**Comment by zuzana** [comment]
Thanks for the prompt reply. The fix you proposed did help and now generated audio sounds good! 👍 
Now I'm onto training student network - thanks for training tip. 
I have one more question, but it is unrelated to this, so I'll open a new issue.
