### ISSUE TITLE
StudentGaussianIAF: different preprocessing length for teacher_params and params

### ISSUE THREAD

**Issue by zuzana** [dhgrs/chainer-ClariNet#5]
Hi, 

is there a reason why 

`StudentGaussianIAF/teacher_params.py` has `length=12000` 
and 
`StudentGaussianIAF/params.py` has `length=24000`

while all other preprocessing params stay the same? 

Thanks.

**Comment by dhgrs** [comment]
3.3.2 Spectrogram Frame Loss in the paper, they say that 0.32s(original Parallel WaveNet) is short length and the clip length in ClariNet is increased. So that I increased the length in Student parameters.
