### ISSUE TITLE
Q: Text-to-Wave Architecture

### ISSUE THREAD

**Issue by zuzana** [dhgrs/chainer-ClariNet#6]
Hi, 

the Clarinet paper mentions also Text-to-Wave Architecture for end-to-end TTS. 

Do you have any suggestions what would I need to do full TTS once the student network is trained?

Should I use some pre-trained model to produce mel-spetrograms like [Tacotron2](https://github.com/NVIDIA/tacotron2) or [DeepVoice3](https://github.com/r9y9/deepvoice3_pytorch)? Or something else entirely?

Thanks!

**Comment by dhgrs** [comment]
I don't have any plans to implement TTS part. But if parameters for calculating mel-spectrograms are same, pre-trained model may be used.

I don't know the parameters that their repositories use. Please check these parameters.
- Sampling rate
  - 22.05kHz in my repo.
- Hop length
  - 300 samples in my repo.
- FFT window length
  - 1024 in my repo.
- Number of mel filters
  - 80 in my repo.
- Mel filterbank setting
  - Same as the default of librosa in my repo.
  - Minimum frequency, maximum frequency and frequency-scale(log or linear) should be same.
- Normalization
  - Mel-spectrograms scaled into [0, 1] in my repo.

**Comment by zuzana** [comment]
Thanks for the information, will report back when I try it out.

**Comment by dhgrs** [comment]
I found that hop length and normalization are different between my repo and NVIDIA/Tacotron2 and others are same.
- Hop length
  - You need to train my ClariNet with `hop_length = 256` and `upsample_factors = [16, 16]` in `params.py`.
  - If hop length is different between Tacotron2 and ClariNet, it may be able to generate audible samples but the speed is changed.
- Normalization
  - You need to normalize the Tacotron2 outputs into [0, 1].
