### ISSUE TITLE
integration with VQVAE for voice transfer

### ISSUE THREAD

**Issue by barby1138** [dhgrs/chainer-ClariNet#8]
Hi,
Do you plan subj?
thanks

**Comment by dhgrs** [comment]
Hi,

I don't have a plan to integrate with VQ-VAE. Because it is hard to train multi-speaker Parallel WaveNet.

I trained multi-speaker vocoder with same setting but the quality is bad. I think we get the network size bigger to apply multi-speaker. But I don't have such machines.
